apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vscode/"