apiVersion: v1
kind: Service
metadata:
  name: vscode-service
spec:
  type: NodePort
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    app: vscode-deployment