apiVersion: v1
kind: Service
metadata:
  name: jplab-service
spec:
  type: NodePort
  ports:
    - port: 8889
      targetPort: 8889
      protocol: TCP
      name: http
  selector:
    app: jplab-deployment